services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: adminpassword
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: "8080"
      KC_PROXY: "edge"
    command: ["start-dev", "--import-realm"]
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/realms:/opt/keycloak/data/import