{{- if .Values.admin.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-secrets-manager
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "patch", "update"]
  resourceNames: ["portcall-secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-secrets-manager
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-secrets-manager
subjects:
- kind: ServiceAccount
  name: admin
  namespace: {{ .Values.global.namespace }}
{{- end }}
