{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.observability.grafana.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.observability.grafana.service.type }}
  selector:
    app: grafana
  ports:
    - name: http
      port: {{ .Values.observability.grafana.service.port }}
      targetPort: {{ .Values.observability.grafana.port }}
{{- end }}
