server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dashboard
    static_configs:
      - targets: [localhost]
        labels:
          job: dashboard
          app: dashboard
          __path__: /var/log/dashboard/*.log
  - job_name: api
    static_configs:
      - targets: [localhost]
        labels:
          job: api
          app: api
          __path__: /var/log/api/*.log
  - job_name: checkout
    static_configs:
      - targets: [localhost]
        labels:
          job: checkout
          app: checkout
          __path__: /var/log/checkout/*.log
  - job_name: billing
    static_configs:
      - targets: [localhost]
        labels:
          job: billing
          app: billing
          __path__: /var/log/billing/*.log
